coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto

  # Ignore everything except the tests directory
  ignore:
    - "**/*"
    - "!tests/**/*"

