name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for gcov and gcovr
        run: |
          choco install llvm  
          pip install gcovr

      - name: Build Test
        working-directory: C++
        run: build.bat

      - name: Run executable in test mode
        working-directory: C++
        run: a.exe -t

      - name: Generate code coverage report
        working-directory: C++
        run: |
          llvm-cov gcov test.cpp
          gcovr -r . --xml -o coverage.xml

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./C++/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          working-directory: C++