name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install cmake llvm
          pip install gcovr

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build Project
        run: |
          cmake --build build

      - name: Run Tests
        run: |
          ctest --test-dir build

      - name: Generate Code Coverage Report
        run: |
          cd build
          llvm-cov gcov TestRun
          gcovr -r .. --xml -o coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: build/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
