name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up MSBuild (if needed)
      #   uses: microsoft/setup-msbuild@v1
      - name: Change to C++ directory
        run: cd C++

      - name: Run build script
        run: ./build.bat

      # - name: Run tests
      #   run: |
      #     # Assuming your build.bat compiles the project and generates an executable or runs tests.
      #     # Replace `your_test_executable.exe` with the name of your actual test executable.
      #     ./path/to/your_test_executable.exe
