name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for gcov and gcovr
        run: |
          choco install llvm  
          pip install gcovr

      - name: Build Test
        run: |
          cmd /c "cd C++ && build.bat"

      - name: Run executable in test mode
        run: |
          cmd /c "cd C++ && a.exe -t"

      # - name: Generate code coverage report
      #   run: |
      #     cmd /c "cd C++ && llvm-cov gcov main.cpp"
      #     cmd /c "cd C++ && gcovr -r . --xml -o coverage.xml"
      
      - name: Install OpenCppCoverage
        run: |
          choco install OpenCppCoverage
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

      - name: Generate Coverage Report
        shell: cmd
        run: | 
          tree /F
          OpenCppCoverage --export_type cobertura:coverage.xml --cover_children -- C++\a.exe

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./C++/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
