name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for gcov and gcovr
        run: |
          choco install llvm  
          pip install gcovr

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build Project
        run: |
          cmake --build build --config Debug

      - name: Run Tests
        run: |
          ctest --test-dir build --output-on-failure --C Debug

      - name: Generate code coverage report
        run: |
          cmd /c "cd build && llvm-cov gcov a.exe"
          cmd /c "cd build && gcovr -r . --xml -o coverage.xml"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./build/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
