name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Test
        run: |
          cmd /c "cd C++ && build.bat"
      # Will add this in later (might get it to run the test files instead of the actual program)
      # - name: Run executable
      #   run: |
      #     cmd /c "cd C++ && a.exe"

      # - name: Run tests
      #   run: |
      #     # Assuming your build.bat compiles the project and generates an executable or runs tests.
      #     # Replace `your_test_executable.exe` with the name of your actual test executable.
      #     ./path/to/your_test_executable.exe
