name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for gcov and gcovr
        run: |
          choco install llvm  
          pip install gcovr

      - name: Build Test
        run: |
          cmd /c "cd C++ && build.bat"
          
      - name: Run executable in test mode
        run: |
          cmd /c "cd C++ && a.exe -t"
          
      - name: Generate code coverage report
        run: |
          cmd /c "cd C++ && llvm-cov gcov test.cpp"
          cmd /c "cd C++ && gcovr -r . --xml -o coverage.xml"

      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
