name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install dependencies for gcov and gcovr
      #   run: |
      #     choco install llvm  
      #     pip install gcovr

      - name: Set up build directory
        id: directory
        run: echo "build-dir=${{ github.workspace }}/build" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          cmake -S ${{ github.workspace }} -B ${{ steps.directory.outputs.build-dir }} -DCMAKE_BUILD_TYPE=Debug

      - name: Build Project
        run: cmake --build ${{ steps.directory.outputs.build-dir }} --config Debug

      - name: Run Tests
        working-directory: ${{ steps.directory.outputs.build-dir }}
        run: ctest --build-config Debug

      - name: Install OpenCppCoverage
        run: |
          choco install OpenCppCoverage
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH

      - name: Generate Coverage Report
        shell: cmd
        run: |
          tree /F
          OpenCppCoverage --export_type cobertura:coverage.xml --cover_children -- ctest -C Debug --test-dir ${{ steps.directory.outputs.build-dir }}

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
